### ISSUE TITLE
Full replacements are (usually) bad

### ISSUE THREAD

**Issue by DorentuZ** [Booo3/red_money#1]
As a general rule for modding: Don't replace things unless you absolutely have to. For example, the hook in [/hooks/moneytweakdata.lua](https://github.com/Booo3/red_money/tree/master/hooks/moneytweakdata.lua) replaces all bag values. That's unnecessary, you can just append the thing to the table:
`self.bag_values.your_new_thing = 12345`

I'm not sure what you changed in [/hooks/elementareatrigger.lua](https://github.com/Booo3/red_money/tree/master/hooks/elementareatrigger.lua) other than externalizing that long `carry_list` table, but you can avoid a full replacement there as well:
```
local project_instigators_orig = ElementAreaTrigger.project_instigators
function ElementAreaTrigger:project_instigators(...)
    if self._values.instigator == "loot" or self._values.instigator == "unique_loot" then
        your new stuff
     end
    return project_instigators_orig(self, ...)
end
```

It's *slightly* slower, but that's usually not that big of a deal when it means not breaking other mods.

And is it really necessary to copy all those assets? I'm not too familiar with that part of PD2 but it doesn't look quite right to me.

**Comment by Booo3** [comment]
@DorentuZ oh yeah forgot to remove /hooks/moneytweakdata.lua i tried some stuff, but never really did anything with it, so i removed it from the main.xml. So it does not even get loaded.

And yes i have to copy all the assets because it speeds up loading.
Instead the map loads the packages with all the units, it just loads that one unit. and there is no better way of doing that when you want to have a lot different units in one map.
